version: "3.7"

services:
    database:
        image: mysql:5.7
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: P123456p
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: tantuni_44
            MYSQL_PASSWORD: Tantuni_44 
        networks:
            - clarusnet
    myapp:
        image: eminecw/bookstore-api:latest
        container_name: myapp
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - clarusnet
networks:
    clarusnet:
        driver: bridge